project_id = "lpuybtjctiffqlabjszc"

[functions.validar-contrato]
verify_jwt = false

[functions.assinar-contrato]
verify_jwt = false

[functions.resetar-contrato]
verify_jwt = false

[functions.reportei-test]
verify_jwt = false