project_id = "lpuybtjctiffqlabjszc"

[functions.validar-contrato]
verify_jwt = false

[functions.assinar-contrato]
verify_jwt = false

[functions.resetar-contrato]
verify_jwt = true

[functions.reportei-test]
verify_jwt = false

[functions.reportei-fetch-data]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false
[functions.payments-webhook]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
