// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fngjxjrgovhxbdlkomvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZuZ2p4anJnb3ZoeGJkbGtvbXZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MzM3NzAsImV4cCI6MjA2MzQwOTc3MH0.raxNJLUgpSlKbUBnRDH3aPVMjQe2XUu3Ujmjo4M3CkY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);